on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set git user and email
        run: |
          git config --global user.name ${{ secrets.MY_NAME }}
          git config --global user.email ${{ secrets.MY_EMAIL }}
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        run: bun run deploy
