on:
  push:
    branches:
      - main

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set git user and email
        run: |
          git config --global user.name $MY_NAME
          git config --global user.email $MY_EMAIL
          git remote set-url origin https://$MY_NAME:${{ secrets.GH_PAT }}@github.com/$MY_NAME/leetdavid.github.io.git
        env:
          MY_NAME: leetdavid
          MY_EMAIL: leetdavidu@gmail.com
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
      - name: Install
        run: bun install
      - name: Build
        run: bun run build
      - name: Deploy
        run: bun run deploy
